### ISSUE TITLE
Error while importing dashboard

### ISSUE THREAD

**Issue by sriharsha-bhasuru** [hometogo/hometogo-data-code-snippets#8]
When using with Superset 3.0 getting below error, I modified the datasources yml file as suggested in the article

![image](https://github.com/hometogo/hometogo-data-code-snippets/assets/16029195/d24f4537-c9f4-4001-b0a2-47bca7057823)

**Comment by jbat** [comment]
@sriharsha-bhasuru 

I am using 4.0.1 .. and got the same error as you.
Looking at the logs showed this.

```
superset_app          |   for uuid, private_key_password in db.session.query(
superset_app          | Error running import command
superset_app          | Traceback (most recent call last):
superset_app          |   File "/app/superset/commands/importers/v1/__init__.py", line 75, in run
superset_app          |     self._import(self._configs, self.overwrite)
superset_app          |   File "/app/superset/commands/dashboard/importers/v1/__init__.py", line 138, in _import
superset_app          |     config = update_id_refs(config, chart_ids, dataset_info)
superset_app          |   File "/app/superset/commands/dashboard/importers/v1/utils.py", line 135, in update_id_refs
superset_app          |     target["datasetId"] = dataset_info[dataset_uuid]["datasource_id"]
```

above error points to the datasets not having the correct UUID that should reference my new database.yaml I uploaded.

Solved the issue through the following steps on my localhost superset instance:

- made a copy of the entire folder in `dashboard_export`
- copied in my database yaml file into `dashboard_export/databases`
- got the UUID of that database yaml file `grep uuid dashboard_export/databases/examples.yaml`
- for all dataset yaml files, replace the entry for database with the value above in examples.yaml

Zip up and import to your SS instance.

![Uploading Screenshot 2024-08-12 at 9.12.30 AM.png…]()

**Comment by jbat** [comment]
Hi @stephanclaus 

I was wondering if you had a more recent version of the Superset Monitoring dashboard 
( given version 1.4 was a few years ago )
and if your willing to share it with the community?
